bitdriftlabs/capture-sdk

platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/AppUpdateListenerLoggerTest.kt

So they can be run inside AS and cmdline

[ANDR] Fix unit tests

---

.bazelrc
README.md

Fixes https://github.com/bitdriftlabs/capture-sdk/issues/13

use hermetic JDK for build/tests

---

.github/workflows/android.yaml
Cargo.Bazel.lock
Cargo.lock
Cargo.toml

This brings in changes to support limiting the size of the flushed session and compression improvements.

update shared-core dependency

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpNetwork.kt
platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/ReplayPreviewClient.kt
platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/ReplayCaptureController.kt

[ANDR] Define custom names for all threads managed by the sdk

---

.github/workflows/integrations_android.yaml
.github/workflows/release_gh.yaml

Fixing issues introduced in #144
Tested it works in brach used here: https://github.com/bitdriftlabs/capture-sdk/actions/runs/12261648491

[andr][ci] Fix release jobs

---

.github/workflows/integrations_android.yaml
ci/capture_android_release.sh
ci/generate_maven_metadata.py

Follow-up to #155, #144
Trying to fix now the final public upload step: https://github.com/bitdriftlabs/capture-sdk/actions/runs/12262986932/job/34214138305

[ci][andr] Fix the public release

---

WORKSPACE
platform/swift/source/replay/SessionReplayTarget.swift

Move screenshots to the main thread

---

platform/jvm/gradle-test-app/src/main/graphql/BookTrips.graphql
platform/jvm/gradle-test-app/src/main/graphql/Login.graphql
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/BitdriftInit.java
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt

This will help when testing the network instant insights dashboards
example session: https://timeline.bitdrift.dev/session/a6458b65-649e-453d-bc74-0459fa7c550f

[andr] Add more diversity of gql operations to demo app

---

platform/swift/source/logging/HTTPRequestInfo.swift

Best effort to support apollo graphql from requests

---

.github/workflows/integrations_android.yaml
.github/workflows/release_gh.yaml
.github/workflows/release_public.yaml
ci/capture_android_release.sh

CI is still broken: https://github.com/bitdriftlabs/capture-sdk/actions/runs/12712471163/job/35438155935#step:9:9

Remove other instances of v3 of apollo in CI

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpApiClient.kt

We already do this for OkHttpNetwork. Without this we may end up leaking connections

ensure we close okhttp response in ApiClient

---

.bazelrc
MODULE.bazel

Following instructions from https://github.com/bazelbuild/apple_support#bazel-7-setup

Fix arm64 libcapture.dylib ci error

---

platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/MainActivity.kt

Settings click on menu wasn't doing anything, now will navigate to configuration as well on the main page.

[ANDR] [GradleTestApp] Navigate to configuration on Settings click

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
Makefile
platform/jvm/src/jni.rs
platform/shared/src/metadata.rs
platform/swift/source/Cargo.toml
platform/swift/source/src/bridge.rs
test/platform/swift/bridging/Cargo.toml

Brings in https://github.com/bitdriftlabs/shared-core/pull/94

bring in Sankey fix from shared-core

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml

Notably this brings in matching on device ID

updated shared-core to the latest main

---

docs/releasing.md

Updating release process to include shared-code

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListener.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureOkHttpEventListenerFactoryTest.kt

More details at https://linear.app/bitdrift/issue/BIT-4704 
Verified session https://timeline.bitdrift.dev/s/b253183b-68d5-440e-9c26-5e2ecc5411e5?utm_source=sdk

[Android] OkHttp Event listener filtering

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListener.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureOkHttpEventListenerFactoryTest.kt

This reverts commit a61a38c3008053cb842e8aa3d91a5fcbf2183dad.

Revert "Filtering for path (#236)"

---

platform/jvm/gradle-test-app/src/main/res/layout/fragment_first.xml

Making content scrollable so is visible across devices/landscape
https://github.com/user-attachments/assets/dd05d4c2-82b3-4d86-aafe-44ccd4b08b49
https://timeline.bitdrift.dev/s/d05e1f61-1490-4137-bf1f-a2718caf70c8?utm_source=sdk

[Android] [Gradle demo app] Allow main content to be scrollable

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/CrashReporter.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CrashReporterTest.kt

Picking up changes from https://github.com/bitdriftlabs/shared-core/pull/115

Bump shared core for file update rename

---

MODULE.bazel
bazel/pom_template.xml
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/CrashReporter.kt

See related PR https://github.com/google/bazel-common/pull/217
Big kudos to @quanturium for the investigation and root cause 🙏

Fix capture pom

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt
platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/ErrorHandler.kt

[Android] Add default for handle error

---

examples/android/HelloWorldApp.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporterState.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporterStatus.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerSessionOverrideTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ErrorReporterTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionStrategyTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionUrlTest.kt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt
platform/jvm/microbenchmark/src/androidTest/java/io/bitdrift/microbenchmark/ClockTimeProfiler.kt

Given will be reporting other type of Fatal issues, renaming CrashReporter to FatalIssueReporter

Rename CrashReporter to FatalIssueReporter

---

examples/android/HelloWorldApp.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt

initFatalIssueReporting still no ready for public. Closing viz

Hide visibility of experimental API

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/AppExitLogger.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/exitinfo/ILatestAppExitInfoProvider.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/exitinfo/LatestAppExitInfoProvider.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/exitinfo/LatestAppExitInfoProviderProvider.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/LatestAppExitInfoProviderTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/fakes/FakeLatestAppExitInfoProvider.kt

Another minor refactor to allow reuse at FatalIssueReporter

[Android] Minor refactor to LatestAppExitInfoProviderProvider

---

tools/swap_local.sh

This should make it easier to iterate on shared-core changes when using the gradle test app which works with the path overrides

add script to point shared-core deps to local repo

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterTest.kt

Minor fix to remove empty spaces on config file

[Android] Remove spaces on csv file

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml

Bringing in https://github.com/bitdriftlabs/shared-core/pull/124

Bump shared-core

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueConfigParser.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporterState.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueConfigParserTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterTest.kt

Demo session https://timeline.bitdrift.dev/s/3fec042c-3af6-469b-9c03-d2afd8ca8ac1?utm_source=sdk

[Android] Add fatal issue path placeholders

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/HttpRequestMetrics.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/HttpResponseInfo.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListener.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureOkHttpEventListenerFactoryTest.kt
platform/swift/source/logging/HTTPRequestMetrics.swift
platform/swift/source/logging/HTTPResponseInfo.swift
test/platform/swift/unit_integration/integrations/URLSessionIntegrationTests.swift

Adding protocol to HTTPResponseInfo

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/AppExitLogger.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/AppExitLoggerTest.kt
platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/Runtime.kt

This was used for internal testing and can be removed now

[Android] Remove send_crash_artifact flag

---

platform/jvm/gradle-test-app/build.gradle.kts
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FatalIssueGenerator.kt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt

Adding a BroadcastReceiver ANR, Coroutines ANR/Crash

[Android] [Gradle app] Adding more fatal issue trigger on sample app

---

platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/StrictModeReporter.kt

Demo session https://timeline.bitdrift.dev/session/5ac10aff-278f-4bb0-b075-f86bfc02a825?utm_source=sdk&pages=1

[Android] [Gradle Test App] Adding strict mode reporting to gradle demo app

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporterState.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterTest.kt

This was a leftover from the initial draft https://github.com/bitdriftlabs/capture-sdk/pull/296 
Resolves BIT-5073

[Android] [FatalIssueReporting]Update state to reflect fatalIssueMechanism

---

.github/workflows/android.yaml

Adding apk size check for bazel test app. For now will print current baseline on follow up PR we can adjust the apk size diff
Resolves BIT-4877

[Android] APK size check

---

.github/workflows/android.yaml

Further tweaks to https://github.com/bitdriftlabs/capture-sdk/pull/346 
We need to upload apk size on latest main as baseline
Will be using this to validate https://github.com/bitdriftlabs/capture-sdk/pull/347

[Android] APK size check - further fix

---

.github/workflows/android.yaml

Minor UI tweak. See on artificial increase https://github.com/bitdriftlabs/capture-sdk/pull/351

[Android] Minor visual tweak for apk size check

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml

Includes PRs below: (since current [774151aeedaab2e772acd073afed3e37ad58dce9](https://github.com/bitdriftlabs/shared-core/pull/137) )
- https://github.com/bitdriftlabs/shared-core/pull/143
- https://github.com/bitdriftlabs/shared-core/pull/142
- https://github.com/bitdriftlabs/shared-core/pull/140
- https://github.com/bitdriftlabs/shared-core/pull/138

Bump shared core

---

.github/workflows/android.yaml

After recent testing android.yaml is not running on latest main push

[Android] Testing if apk size caching is working

---

platform/shared/src/metadata.rs

remove must_use

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/parser/FatalIssueConfigParser.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/AppExitAnrTraceProcessor.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/FatalIssueReporterProcessor.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterProcessorTest.kt

Resolves BIT-5378
Adding ANR types as the reason for AppExit ANR
- Currently on main
https://timeline.bitdrift.dev/session/1b479b2d-bbe8-4984-a98f-93affb76f72f?utm_source=sdk&pages=1&utilization=0&expanded=3223018819215494859
- On PR
https://timeline.bitdrift.dev/s/b5ad76f1-de87-4b43-bde5-4b0bfc43db81?utm_source=sdk

[Android] [FatalIssueReporting][BuiltIn] Append reason for ANR case

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
examples/android/HelloWorldApp.kt
platform/jvm/capture/BUILD.bazel
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/persistence/FatalIssueReporterStorage.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/AppExitAnrTraceProcessor.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterProcessorTest.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterStorageTest.kt
platform/jvm/capture/src/test/resources/BUILD.bazel
platform/jvm/capture/src/test/resources/app_exit_anr_deadlock_anr.txt
platform/jvm/capture/src/test/resources/app_exit_native_crash.txt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt

Prepares for Android BuiltIn Release, includes:
- shared-core bump: https://github.com/bitdriftlabs/shared-core/pull/155
- Exposing BuiltIn mechanism only for Android (iOS will be in a separate release)
- Swap ANR fields for better viz on Issue Group
- Update JUnit test to read from raw reports

[Android] [FatalIssueReporter] Preparing for BuiltIn Release

---

platform/swift/source/default/events/memory/DispatchSourceMemoryMonitor.swift

See https://developer.apple.com/forums/thread/769833 for more information

Guard `MemoryPressureEvent` for a compiler bug

---

platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt
platform/jvm/gradle-test-app/src/main/res/layout/fragment_first.xml

Only a few minor UI tweak to ease Fatal Issue Reporting testing (before always need to scroll down to app exit button). Also fixed dropdown selector for `Log Message` type

[Android] Gradle test app - Minor visual tweaks

---

.github/workflows/license.yaml
Cargo.Bazel.lock
Cargo.lock
Cargo.toml
platform/jvm/src/jni.rs

Resolves BIT-550 by including fix https://github.com/bitdriftlabs/shared-core/pull/165
Related thread https://bitdrift.slack.com/archives/C058ZD2M2CQ/p1749117566334359

[Android] Bump shared core for SessionStrategy deadlock fix

---

platform/swift/source/src/bridge.rs

This was missed on this bump https://github.com/bitdriftlabs/capture-sdk/pull/424

Remove unavailable function

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/ClientAttributes.kt
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/utils/BuildTypeChecker.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ClientAttributesTest.kt

This is another important info to know where the app is installed when issues arise
Sample Capture Start log emission https://timeline.bitdrift.dev/session/693c2c1e-e586-42e3-92e3-1a3598da0b4e?utm_source=sdk&pages=1&utilization=0&expanded=5982843070888075131

[Android] Add installation source

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Configuration.kt

So will read a bit better on docs for fatal issue

[Configuration] Reorder params for JvmOverloads

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/AppExitAnrTraceProcessor.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterProcessorTest.kt

Resolves BIT-5142
Related to https://github.com/bitdriftlabs/bitdrift-frontend/pull/2382
Add thread information for ANR reports
[Report](https://explorations.bitdrift.dev/issues/9221982903175203465/6e135a2e-b3ac-4b77-bcd0-1c318dc0d85e?range=1d) (Scroll through threads)
**_NOTE: To render thread id and thread state will need https://github.com/bitdriftlabs/bitdrift-frontend/pull/2382_**

[Android] Append thread info for ANR case

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/JvmCrashProcessor.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterProcessorTest.kt

Resolves BIT-5699
We weren't handling nested stacktraces for BuiltIn mode.
**NOTE: As a follow up will update issues frontend to apply same rendering logic for chained exception as displayed in timeline**
[Session](https://timeline.bitdrift.dev/session/1178c5e2-d2c3-4c71-b833-e99f64346f0f?utm_source=sdk&pages=1&utilization=0&expanded=3826380455842820759&stacktrace=open)
Steps:
1. Open GradleTestApp
2. Trigger APP_CRASH_RX_EXCEPTION app exit
3. Relaunch app
[Session](https://timeline.bitdrift.dev/session/d52fb55a-8cc0-4f80-b9a5-98f9c45a995f?utm_source=sdk&pages=1&utilization=0&expanded=2511429313127355616&stacktrace=open)
Steps:
1. Open GradleTestApp
2. Trigger APP_CRASH_REGULAR_JVM_EXCEPTION app exit
3. Relaunch app

[Android] [Fatal Issue] Support nested stack trace

---

.github/workflows/android.yaml
platform/jvm/microbenchmark/src/androidTest/java/io/bitdrift/microbenchmark/ClockTimeProfiler.kt

This has been broken for a while given the recent changes on LoggerImpl constructor
Related to https://github.com/bitdriftlabs/capture-sdk/pull/489
Run those locally on real device

[Android] Fix microbenchmark

---

platform/jvm/capture/BUILD.bazel
platform/jvm/capture/build.gradle.kts
platform/jvm/gradle/libs.versions.toml
platform/jvm/replay/build.gradle.kts

Resolves https://github.com/bitdriftlabs/capture-sdk/issues/98

Remove mockito inline

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpApiClient.kt

Cleaning up an accidental leftover from https://github.com/bitdriftlabs/capture-sdk/pull/180

[Android] Remove unnecessary Log.e

---

.github/actions/common-android-setup/action.yaml
.github/workflows/android.yaml
.github/workflows/example_apps_android.yaml
.github/workflows/integrations_android.yaml
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/ReportFrameBuilder.kt

Resolves BIT-5969
Consolidation of Android common cmd line tools/NDK into a dedicated common action

[Android] CI setup consolidation

---

.github/workflows/release_public.yaml

broke in https://github.com/bitdriftlabs/capture-sdk/pull/585/files#diff-c37fba4959de228884e57bbe59f2bd8562c1753d2641462e2cd0e14d326c3556L64

undo unnecessary gh permission

---

MODULE.bazel
bazel/BUILD.bitdriftlabs_api
proto/BUILD

- Pin the api dependency to a commit
- Fix the Bazel rules to handle common.fbs

fix flatbuffer import after api changes

---

.github/workflows/release_capture_react.yaml

To retrieve worflow id
`gh workflow list --repo bitdriftlabs/capture-es`

Update capture-es workflow id

---

.github/workflows/android.yaml
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/jvmcrash/CaptureUncaughtExceptionHandler.kt
tools/capture_so_size.sh

Follow up to previous attempt https://github.com/bitdriftlabs/capture-sdk/pull/378
Sample output

Update action to include .so size

---

examples/android/HelloWorldApp.kt
examples/swift/hello_world/LoggerCustomer.swift
platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Configuration.kt
platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt
platform/swift/source/LoggerObjc.swift
platform/swift/source/features/Configuration.swift

Depends on https://github.com/bitdriftlabs/capture-sdk/pull/603
Configuration will have now `enableFatalIssueReporting ` set to true by default

Enable fatal issue reporting by default

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
platform/swift/source/src/bridge_tests.rs
test/platform/jvm/Cargo.toml

https://github.com/bitdriftlabs/shared-core/pull/228

bump shared core for improved crash loop detection

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/ClientAttributes.kt
platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/attributes/ClientAttributesTest.kt

Verified [here](https://timeline.bitdrift.dev/session/d45fc291-df02-4461-844d-3769446c554f?utm_source=sdk&pages=1&utilization=0&expanded=-5195446213895562071)

Fix casing on OOTB field

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt

Mark features flag API as experimental

Mark feature flag APIs as experimental

---

examples/android/HelloWorldApp.kt
gradle/app/build.gradle

As a followup we should probably auto update this on release as well

[Android] Bump version for the gradle integration app

---

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/AppExitLogger.kt

Remove left over WorkerThread annotation
