bitdriftlabs/capture-sdk

platform/jvm/capture-apollo3/build.gradle.kts, platform/jvm/capture-timber/build.gradle.kts, platform/jvm/capture/build.gradle.kts, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/ErrorHandler.kt, platform/jvm/common/build.gradle.kts, platform/jvm/gradle-test-app/build.gradle.kts, platform/jvm/gradle.properties, platform/jvm/gradle/libs.versions.toml, platform/jvm/gradle/wrapper/gradle-wrapper.properties, platform/jvm/replay/build.gradle.kts, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/WindowManager.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/mappers/TextMapper.kt
Simplify (and make fwd compatible) the lint gradle task configuration on the `gradle-test-app`. Also run the same configuration in all of our artifact modules (and suppress any existing warnings).
In order to make this work we had to downgrade gradle from 8.3 --> 8.2 due to this open bug: https://issuetracker.google.com/issues/332755363
=> [ANDR][dev] Run lint on every project and apply same config everywhere

examples/README.md
- Add rust installation instructions
- Update NDK version
- Add bazel test instructions
=> Update android example setup README.md

.bazelrc
Move --java_runtime_version=remotejdk_11 to test only as this is the only place it is needed and it conflicts with the Android toolchain during real builds.
=> more bazelrc fixes

ci/check_bazel.sh, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ClientAttributesTest.kt
Quick fix for `$GITHUB_BASE_REF` being empty on `main` branch runs (variable is only available on pull requests: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables )
Fixes #27
=> [ci] Fix bazel check for changes

.github/workflows/android.yaml, ci/check_bazel.sh, ci/files_changed.sh, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt
Follow up from https://github.com/bitdriftlabs/capture-sdk/pull/24 and https://github.com/bitdriftlabs/capture-sdk/pull/28
This PR fixes:
- https://github.com/bitdriftlabs/capture-sdk/actions/runs/10781042749/job/29898099793 👇
```
Check for workflow file changes
Run ./ci/files_changed.sh .github/workflows/android.yaml
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
No relevant changes found.
```
```
Check for relevant Gradle changes
Run ./ci/files_changed.sh "^platform/jvm/gradle-test-app/.*\.(gradle|kts|kt|xml)$"
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like …
```
=> [ci] Fix `files_changed` `merge` main issues and `files_changed` and `check_bazel` script's `base_sha` to point to `HEAD~1`

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/common/PowerMonitor.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/device/DeviceStateListenerLogger.kt
Customers have reported encountering certain devices (particularly the Caterpillar S48C phone) where `context.getSystemService(Context.POWER_SERVICE)` would be `null` causing our `Logger.configure()` method to throw.
=> [sdk][andr] Don't use PowerManager if not available

ci/capture_android_release.sh
Since the source is now available we should include the sources jar for ease of development and debugging on consumer apps.
=> [andr][releases] Include sources.jar artifact in maven releases

platform/jvm/microbenchmark/src/androidTest/java/io/bitdrift/microbenchmark/ClockTimeProfiler.kt
Reported numbers on a Pixel 7A:
```
7,248,567   ns        3509 allocs    Trace    Method Trace    ClockTimeProfiler.loggerStart
51,743   ns          41 allocs    Trace    Method Trace    ClockTimeProfiler.logNotMatchedNoFields
83,706   ns          98 allocs    Trace    Method Trace    ClockTimeProfiler.logNotMatched5Fields
113,163   ns         134 allocs    Trace    Method Trace    ClockTimeProfiler.logNotMatched10Fields
```
=> [andr][tests] Profile Logger creation

platform/jvm/gradle-test-app/src/androidTest/java/io/bitdrift/gradletestapp/ComposeReplayTest.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/ScannableView.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/compose/ComposeTreeParser.kt
This took an embarrassingly long time to figure out, but after following the rabbit hole in https://github.com/androidx/androidx/blob/48f6421f6615572456ee94984209cd110a4694d4/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/accessibility/android_a11y_implementation_notes.md#androidview-children I realized that the Compose LayoutNode has an (internal) reference to the legacy AndroidView if it exists.
In the example below we're creating an hybrid view via: https://github.com/bitdriftlabs/capture-sdk/blob/f6edcc166a5f4bb1c9a5c6e1d2f6bcc1ddf89c1f/platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/ComposeScreen.kt#L82-L91
|Screen|Before|After|
|---|---|---|
|<img width="277" alt="Screenshot 2024-11-18 at 10 52 38 AM" …
=> [andr][replay] Handle hybrid AndroidViews inside Compose

platform/jvm/gradle-test-app/src/androidTest/java/io/bitdrift/gradletestapp/ComposeReplayTest.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/ComposeScreen.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/compose/CaptureModifier.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/compose/CaptureModifier.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/compose/ComposeTreeParser.kt
|(current)|`captureIgnore(ignoreSubTree = false)`|`captureIgnore(ignoreSubTree = true)`|
|---|---|---|
|![Screenshot 2024-11-20 at 7 15 46 PM](https://github.com/user-attachments/assets/96877f91-4507-4d41-ab45-09c727f0c286)|![Screenshot 2024-11-20 at 7 14 32 PM](https://github.com/user-attachments/assets/8ca9d38d-d81f-4741-85df-c8b6bd2154cb)|![Screenshot 2024-11-20 at 7 14 44 PM](https://github.com/user-attachments/assets/c9702f8a-8a30-432b-b445-ef4f8d6a38f4)|
=> [andr][replay] Add support for ignoring Compose elements via Modifiers

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/ResourceUtilizationTarget.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerTest.kt
=> Run ResourceUtilization log processor on the correct 'event-listener' thread

.github/workflows/integrations_android.yaml, .github/workflows/release_gh.yaml, .github/workflows/release_public.yaml
The .zip file is redundant since the upload/download actions automatically use zip for directories
=> [andr][ci] Make more fixes for the side libraries release

.github/workflows/integrations_android.yaml, .github/workflows/release_gh.yaml, .github/workflows/release_public.yaml, ci/capture_android_release.sh
The gradle plugin requires an additional artifact to be uploaded in order to get picked up by gradle
=> wire up release of the gradle plugin marker

Cargo.Bazel.lock, Cargo.lock, Cargo.toml, platform/swift/source/src/bridge.rs, test/platform/jvm/src/lib.rs
Due to another change in shared-core in which I removed the "test-logger" feature we have an issue where we are double initializing the logging on iOS tests. I did a targeted fix for this and we can see how it goes.
=> bump shared-core to bring in delay timer fixes

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/EventsListenerTarget.kt
This used to be in place but it must have regressed around the time we moved the core listener logic to rust.
=> [andr] Guard against subscribing more than once to event listeners

ci/capture_android_release.sh
The new plugin directory structure has a nested artifact within the artifact directory for the capture-plugin which messes up the script that tries to pull all the published releases. This should ignore that nested directory 
Fixes BIT-4242
=> fix publishing of capture plugin

platform/jvm/capture-apollo3/src/main/kotlin/io/bitdrift/capture/apollo3/CaptureApolloInterceptor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureOkHttpEventListenerFactoryTest.kt
That way the instant Insights > network dashboard will autopopulate with the operation names
=> [andr] Override _path_template field with gql operation

.github/workflows/update_sdk_version.yaml
Attempt to fix error: https://github.com/bitdriftlabs/capture-sdk/actions/runs/12809837288/job/35715520945#step:6:7
`aborted: you must first push the current branch to a remote, or use the --head flag`
=> [ci] Fix release auto-pr creation

platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/mappers/ViewMapper.kt
Avoid calling getResourceEntryName() when we know it's an invalid id
=> [andr] Avoid noisy replay logs

platform/jvm/BUILD.bazel, platform/jvm/capture/build.gradle.kts
Potential fix for building issues on previous 0.16.9 attempt (see previous failure on https://github.com/bitdriftlabs/capture-sdk/actions/runs/12916680190/job/36022967272)
Will follow similar steps listed on prior PR's description https://github.com/bitdriftlabs/capture-sdk/pull/173 
Check that Android test app is https://developer.android.com/guide/practices/page-sizes
=> [ANDR] Adding linker flags to only android platform

.bazelrc, .github/workflows/ios.yaml, platform/swift/source/BUILD, platform/swift/source/ObjCWrapper.h, platform/swift/source/ObjCWrapper.mm, platform/swift/source/integrations/url_session/URLSessionIntegration.swift, platform/swift/source/integrations/url_session/extensions/URLSessionTask+Swizzling.swift, test/platform/swift/unit_integration/core/BUILD, test/platform/swift/unit_integration/integrations/URLSessionIntegrationTests.swift, test/platform/swift/unit_integration/mocks/BUILD
Setting a delegate on a "Background Task" throws an objc exception that we cannot catch on swift, so we are adding an objc helper to be able to catch those objc `@throw`s
=> Capture objc exceptions on task delegate

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/SessionReplayTarget.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpNetwork.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/threading/CaptureDispatcher.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/threading/CaptureDispatchers.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerNetworkTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerSessionOverrideTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerTest.kt, platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/SessionReplayController.kt
This is a follow up from @murki on https://github.com/bitdriftlabs/capture-sdk/pull/128/files#diff-118bdebccae8c1bde50314ef9d78f897d272e1f222d57a5d8a44d4f0f348b5d4R13 that proposes to consolidates all existing ExecutorService
This will be useful later on for https://github.com/bitdriftlabs/capture-sdk/pull/205 
Verify sessions are captured in same manner and existing thread names remain the same:
- io.bitdrift.capture.event-listener
- io.bitdrift.capture.network.okhttp
- io.bitdrift.capture.session-replay
=> [Android] Consolidate existing ExecutorServices

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/AppExitLogger.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpNetwork.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/threading/CaptureDispatchers.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/AppExitLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ResourceUtilizationTargetTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/fakes/FakeBackgroundThreadHandler.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/fakes/FakeMemoryMetricsProvider.kt, platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/IBackgroundThreadHandler.kt, platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/MainThreadHandler.kt
Following up on https://linear.app/bitdrift/issue/BIT-4410 proposing to make expensive AppExit methods a non-blocking call. This is given the potential impact on main thread as Capture.Logger.start() is going to be usually called on Application/Main activity onCreate
Local measurements shows that building and initializing AppExit is the main contributor to Capture.Logger.start() time.
- Verified that crash/app exit terminations are reported successfully
- Verified that the session id is correct
- Validate improvements on main thread of Capture.Logger.start() call on low end device
- Modify existing microbenchmarks to measure with installAppExitLogger on main vs background
**NOTE: Please note that the whole method doesn't get executed given that there are no exit reasons so we early exit …
=> [Android] Move expensive AppExitLogger methods off the main thread

platform/jvm/capture/build.gradle.kts, platform/jvm/common/build.gradle.kts, platform/jvm/replay/build.gradle.kts
This sets up maven local as a publishing target for enough modules for us to be able to test the RN interaction
Running 
```
./gradlew publishMavenPublicationToMavenLocal -PVERSION_NAME=<version>
```
will now publish artifacts to maven local
=> gradle: allow publishing artifacts to maven local

platform/swift/source/LoggerBridge.swift, test/platform/swift/unit_integration/core/LoggerTests.swift
There seems to be a bug in the swift compiler that makes the literal on file protection crash under certain conditions.
=> Workaround for file protection literal

platform/swift/source/integrations/url_session/URLSessionTaskTracker.swift, platform/swift/source/integrations/url_session/extensions/URLSessionTask+Swizzling.swift, test/platform/swift/unit_integration/integrations/URLSessionIntegrationTests.swift
Before we were checking for specific unsupported task types, flipping it around because we keep finding Task's types iOS throws ObjC runtime exceptions when accessing certain properties.
=> Confirm explicit support for URLSessionTask(s)

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt
Kudos to @murki for the investigation
In order to retrieve more accurate total jank frame duration, adding API level check
=> [Android][Dropped Frames] Add API level checks for duration

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/JankStatsMonitorTest.kt, platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/Runtime.kt
Tech spec https://docs.google.com/document/d/1KPu7DZEl6qzI8P4s5WNr-yqg4DJQkzLcHg9RPWAJVTQ/edit?tab=t.t6ha7ymkk1n2
Adding another config threshold for what is considered Jank.
On local testing and changing to more strict heuristics value was still getting frames reported as janks below 16 ms (e.g. 4 ms)
In this manner we can also control a bit more the lower threshold in case this becomes super noisy
=> [Android] [Dropped Frames] Adding another config value for min threshold

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/HttpRequestMetrics.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/HttpResponseInfo.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListener.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureOkHttpEventListenerFactoryTest.kt, platform/swift/source/logging/HTTPRequestMetrics.swift, platform/swift/source/logging/HTTPResponseInfo.swift, test/platform/swift/unit_integration/integrations/URLSessionIntegrationTests.swift
android example session: https://timeline.bitdrift.dev/session/d492111c-651f-4c2b-b1c7-4ccc5a94e851?pages=1&utilization=0&h=6442453973147137303
=> More metrics to our network responses captures

platform/jvm/BUILD.bazel
This passes -Wl,--build-id during linking for the release build which should make it easier to symbolicate frames coming from the libcapture.so binary
=> include build-id in release android builds

platform/swift/source/RuntimeVariable.swift
Tenants have it enabled and have been running with it for months so it should be safe to default-enable it in the sdk to avoid flip-flopping
=> [sdk][ios] enable anr runtime flag

platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/BitdriftInit.java, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/ConfigurationSettingsFragment.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt
Just small tweak on the gradle test app in order to easy tweak SessionStrategy type without having to hardcode it locally (default still remains as Fixed)
=> [Android] [GradleTestApp] Add session strategy configuration option

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt
Verified with leakcanary enabled on debug build and that dropped frames are still being send upon configuration changes
https://timeline.bitdrift.dev/session/1d4ca361-3037-43d0-b449-3085fbb06b90?pages=1&utilization=0&expanded=1070970770558996757
=> [Android] Memory Leak fix on JankStatsMonitor

examples/android/HelloWorldApp.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/experimental/ExperimentalBitdriftApi.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/CrashReporter.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/CrashReporterState.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/CrashReporterStatus.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/utils/SdkDirectory.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerSessionOverrideTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CrashReporterTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ErrorReporterTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/Mocks.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionStrategyTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionUrlTest.kt, platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/MainThreadHandler.kt, platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/Runtime.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt, platform/jvm/microbenchmark/src/androidTest/java/io/bitdrift/microbenchmark/ClockTimeProfiler.kt
- Introduce "experimental" `Capture.Logger.initCrashReporting` API.
- Status of that init function is passed to LoggerImpl (called upon first Capture.Logger.start), there will append additional map values to existing SDKConfigured . This contains the status of crash reporter and its duration when applicable
- For now opting for a config format such as 'root_directory_path,file_extension'. 
- Appended the epoch time of the original crash file that will be moved under reports/new
- Demo sessions [bazel sample app](https://timeline.bitdrift.dev/session/f150649a-1da8-4732-bf20-4b3b61226272?pages=1&utilization=0&expanded=4568865902884925366), [gradle sample app](https://timeline.bitdrift.dev/s/dddb3ced-0bc6-4078-9044-b90ef98c4022?utm_source=sdk)
=> [Android] Initial proposal for pre init crash reporting method

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/JankStatsMonitorTest.kt
Looks like there are reports with an overflown ms duration (more details on BIT-4813), on this PR the goal is to check for any potential incorrect duration on JankStats and log an error if that's the case
=> [Android] [JankStats] Add error reporting for cases where JankStats API returns unexpected duration

MODULE.bazel, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/CrashReporter.kt
Related to https://github.com/bitdriftlabs/capture-sdk/pull/256
Updating to latest sha on main, now that https://github.com/google/bazel-common/pull/217 is landed
=> [Bazel common] Update to latest sha with fixes on main

Cargo.Bazel.lock, Cargo.lock, Cargo.toml, platform/jvm/src/ffi.rs, platform/jvm/src/jni.rs, platform/shared/src/lib.rs, platform/swift/source/Cargo.toml, platform/swift/source/src/bridge.rs, platform/swift/source/src/ffi.rs, platform/test_helpers/src/lib.rs, test/benchmark/src/bin/live_benchmark.rs, test/benchmark/src/bin/logger_benchmark.rs
This brings in a number of changes relating to crash handling and some changes to the log fields interface that required a few changes 
This seems to increase the binary size by a bit so we should decide whether we want to block this on figuring out how to claw back some of the binary size loss
=> Bump shared core

platform/swift/source/integrations/url_session/ProxyURLSessionDelegate.swift, test/platform/swift/unit_integration/integrations/URLSessionIntegrationTests.swift
When using URLSession without swizzling and with:
- A custom delegate set (uncommon)
- Said delegate does not include the method `(_, task:didFinishCollecting:)`
Given this weird optional check we were not properly proxying the `didFinishCollecting` method to our own and therefore missing network responses.
IMO this should be a compiler warning/error.
=> Fix URLSession proxy targeting

Cargo.Bazel.lock, Cargo.lock, Cargo.toml
This brings in a fix to use the correct unit when inferring the timestamp of a crash report
=> bring in timestamp fix from shared-core

tools/swap_local.sh
Just a minor update so you can pass your custom path to shared-core
Verified Cargo.toml path gets modified correctly and can build from shared-core local repo
=> Minor update to swap_local.sh

platform/jvm/gradle-test-app/build.gradle.kts, platform/jvm/gradle-test-app/src/androidTest/java/io/bitdrift/gradletestapp/AndroidViewReplayTest.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/ApiKeySettingsDialog.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FatalIssueGenerator.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FatalIssueSimulator.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/MainActivity.kt, platform/jvm/gradle-test-app/src/main/res/layout/divider.xml, platform/jvm/gradle-test-app/src/main/res/layout/fragment_first.xml, platform/jvm/gradle-test-app/src/main/res/menu/menu_main.xml, platform/jvm/gradle-test-app/src/main/res/values-night/themes.xml, platform/jvm/gradle-test-app/src/main/res/values/colors.xml, platform/jvm/gradle-test-app/src/main/res/values/strings.xml, platform/jvm/gradle-test-app/src/main/res/values/themes.xml
- Adding more FatalIssue type into gradleTestApp
- Minor UI tweaks (e.g. adding night mode switch in menu for easier theme changes)
- Demo session with OOM crash https://timeline.bitdrift.dev/session/b7692479-76c6-451e-b882-e466bcc201aa?pages=1&utilization=0&expanded=-7278528259014036847
| Old Layout with a new Force App Exit type                                                                                | Dark Mode                                                                                  | Light Mode                                                                                 | Switch App Theme                                                                          | Force Exit Options                                                                       | …
=> [Android] Add more Fatal Issue types into gradle sample app

platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FatalIssueGenerator.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt
You can use this one
```
Process: io.bitdrift.gradletestapp, PID: 805
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.Throwable: Artificial exception
at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:63)
at io.reactivex.rxjava3.internal.operators.observable.ObservableErro …
```
=> [Android] Add composite crash exception to gradle test demo app

platform/jvm/common/src/main/kotlin/io/bitdrift/capture/common/Runtime.kt
This is follow up to BIT-5044 to make RuntimeConfig be explicit about the initial default value
iOS looks ok already, see https://github.com/bitdriftlabs/capture-sdk/blob/main/platform/swift/source/RuntimeVariable.swift
=> [Android] Update runtime config to always specify initial value

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt
- This will prevent any runtime crashing while trying to get a valid context. Prior PR for context https://github.com/bitdriftlabs/capture-sdk/pull/254 where APP_CONTEXT was initially added as lazy
- Related to BIT-5113
=> [Android] FatalIssueReporting app context fix

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterTest.kt
Allow sdk consumers to explicitly pass a context instant when initializing crash reporting. This is particularly useful when they want to call our `initFatalIssueReporting()` method from a content provider since they can do:
```kotlin
override fun onCreate(): Boolean {
@OptIn(ExperimentalBitdriftApi::class)
Capture.Logger.initFatalIssueReporting(getContext())
Bugsnag.start(getContext()!!, "bugsnag_apikey")
return true
}
```
This is an alternative proposal to #307
=> [andr] Allow to explicitly pass context to init() method

bazel/BUILD.bitdriftlabs_api, proto/BUILD
This needed now given we have [multiple fbs](https://github.com/search?q=repo%3Abitdriftlabs%2Fapi+fbs&type=code) in api now
```
ERROR: /home/runner/work/capture-sdk/capture-sdk/proto/BUILD:4:26: declared output 'proto/buffer_log.schema.json' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /home/runner/work/capture-sdk/capture-sdk/proto/BUILD:4:26: Generating flatbuffer files for descriptor: //proto:descriptor failed: not all outputs were created or valid
```
Discussed here https://bitdrift.slack.com/archives/C058ZD2M2CQ/p1745949413605059
=> Fixing main build errors

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/providers/MetadataProvider.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/MetadataProviderTest.kt
Looks like we are creating 2 instances of ErrorHandler unnecessarily
=> [Android] Avoid creating additional ErrorHandler instance

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/JankStatsMonitorTest.kt
Resolves BIT-4820
The theory here is that _duration_ms is a frequently used field that can get triggered on other events relying on this, so the proposal here is to update the event with a more explicit name
This depends on https://github.com/bitdriftlabs/bitdrift-frontend/pull/2236 being deployed
Verified with client changes emitting `_frame_duration_ms` and existing `_duration_ms`
=> [Android] [BIT-4820] Fix frame duration workflow

platform/jvm/replay/src/main/kotlin/io/bitdrift/capture/replay/internal/ScreenshotCaptureEngine.kt
Caught this when a customer enabled the experimental feature for a day (~54 incidences)
=> [android] Avoid crashing when modern pixel copy fails

.github/workflows/android.yaml
This job didn't save the latest apk size properly https://github.com/bitdriftlabs/capture-sdk/actions/runs/14980657611/job/42083886389
Run actions/cache/save@v3
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/capture-sdk/capture-sdk --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key apk-main-baseline, another job may be creating this cache.
Warning: Cache save failed.
=> Apk size fix for caching main 

.github/workflows/android.yaml
Trying with a new name to see we can get around the error below on main
```
Run actions/cache/save@v3
8
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/capture-sdk/capture-sdk --files-from manifest.txt --use-compress-program zstdmt
9
Failed to save: Unable to reserve cache with key apk-main-baseline, another job may be creating this cache.
10
Warning: Cache save failed.
```
This is temporary given I'm working on adding check for aar instead https://github.com/bitdriftlabs/capture-sdk/pull/378
=> Minor polish on build_and_compare_apk

examples/android/HelloWorldApp.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt, platform/swift/source/Capture.swift, platform/swift/source/reports/CrashReportingIntegration.swift
Given BuiltIn is not quite ready, hiding from init the BuiltIn mechanism and defaulting to Integration (same as latest release)
=> [FatalIssueReporting][BuiltIn] Hide public api since is not ready yet

platform/swift/source/LoggerBridge.swift, test/platform/swift/unit_integration/core/LoggerTests.swift
This fixes a legacy case of apps on a broken state where the app asks for complete protection but the buffer was created before we changed the directory permissions.
=> Fix buffer permissions for legacy reasons

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/AppExitLogger.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/FatalIssueReporter.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/IFatalIssueReporter.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/AppExitLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ErrorReporterTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionStrategyTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionUrlTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/fakes/FakeFatalIssueReporter.kt
See demo session here https://timeline.bitdrift.dev/session/74db95e7-ab92-4fb1-a1f4-94c12df35baa?utm_source=sdk&pages=1&utilization=0&expanded=1057666215724288368
_**NOTE: This can be merged now given we are not opening built in to public yet. See https://github.com/bitdriftlabs/capture-sdk/pull/394**_ 
| Before (on local frontend version) | After (on local frontend version) |
|------- |-------|
| <img width="1126" alt="image" src="https://github.com/user-attachments/assets/b8c0b0c2-51b2-4106-8d69-75d01280d3b4" /> | <img width="1108" alt="image" src="https://github.com/user-attachments/assets/d9cd0317-bfcd-4289-86c5-cbbc1ed6d1aa" />|
=> [Android] [Fatal Issue Reporting] Avoid sending duplicated JVM crash log when BuiltIn is configured

test/platform/swift/unit_integration/core/DeviceAttributesTests.swift
This test should only be checking that the locale is valid (rather than checking for a specific locale), so that it can be run in different locales without failing.
=> Make the locale checking test more robust

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/lifecycle/AppExitLogger.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/exitinfo/ILatestAppExitInfoProvider.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/exitinfo/LatestAppExitInfoProvider.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/AppExitLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerSessionOverrideTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/LatestAppExitInfoProviderTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/fakes/FakeLatestAppExitInfoProvider.kt, platform/jvm/gradle-test-app/src/main/AndroidManifest.xml, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/WebViewFragment.kt, platform/jvm/gradle-test-app/src/main/res/layout/fragment_first.xml, platform/jvm/gradle-test-app/src/main/res/layout/fragment_web_view.xml, platform/jvm/gradle-test-app/src/main/res/navigation/nav_graph.xml, platform/jvm/gradle-test-app/src/main/res/values/strings.xml
- BIT-5474 
- [Conversation](https://bitdrift.slack.com/archives/C0891AS6H9Q/p1748902136838469)
- [Investigation doc](https://docs.google.com/document/d/1hxhVkwt8LB5YP-bpDz1RT9_DUqwOnUq3zkf60-rBPuY/edit?tab=t.0#heading=h.i35k1euojnjk) 
- Hardens logic at `LatestAppExitInfoProvider` in order to only get the latest exit info related to the app process
- Add new error logs for Empty and early return when process state summary cannot be retreived
- Add WebView with multiprocess config to Gradle demo app
1. Navigate to a WebView and force kill the app from this view, next app launch should report ApplicationExitInfo info on next timeline event. [See session](https://timeline.bitdrift.dev/session/5bf6c062-1e5d-430b-8377-f133e5b68b22?utm_source=sdk&pages=1&utilization=0&expanded=-4119633971900641 …
=> [Android] Harden AppExitInfo logic

platform/jvm/capture-plugin/src/test/kotlin/io/bitdrift/capture/instrumentation/fakes/TestSpanAddingParameters.kt
The interface to `SpanAddingClassVisitorFactory.SpanAddingParameters` has changed, but `TestSpanAddingParameters` has not been updated to match.
Add a default "true" property to satisfy the new interface.
=> Add missing proxyOkHttpEventListener property in the unit tests

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/Capture.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/IPreInitLogFlusher.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/PreInitInMemoryLogger.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/span/Span.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerSessionOverrideTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ConfigurationTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ErrorReporterTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/PreInitInMemoryLoggerTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionStrategyTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/SessionUrlTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/fakes/FakePreInitLogFlusher.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/ComposeScreen.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/WebViewFragment.kt
- Forces internals of Logger.start() to always happen of the main thread
- Add temporary in memory cache for any Logger.log(*) calls that happen during Logger.start() gets initialized
[Session](https://timeline.bitdrift.dev/session/4d4871db-296e-4e31-9d77-860b83ac8648?utm_source=sdk&pages=1&utilization=0&expanded=5334525886215530043) with a simulated expensive LoggerImpl creation and logs being emitted while start is in process
=> [Android] Force start to run off main thread

platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/BitdriftInit.java, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/GradleTestApp.kt, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/StrictModeReporter.kt
Resolves to BIT-5479
Removes known top offenders from gradle test app that we don't have any control.
**_NOTE: Also added leftover test for session id changed from [see context](https://bitdrift.slack.com/archives/C058ZD2M2CQ/p1749117566334359)_**
| Before | After |
| -------| ------|
| <img width="966" alt="image" src="https://github.com/user-attachments/assets/774bba53-ce70-4354-95ab-b3d796e11bec" /> |  <img width="979" alt="image" src="https://github.com/user-attachments/assets/9a5b9606-1fbc-4b4e-ae27-92ddf74e97c8" /> |
=> [Android] [StrictMode] Ignore known offenders from gradle test app

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/events/performance/JankStatsMonitor.kt
While prepping for my droidcon talk I realized we never copy the volatile data like [the docs say](https://developer.android.com/topic/performance/jankstats#reporting) (and like I suggested here: https://github.com/bitdriftlabs/capture-sdk/pull/222#discussion_r1962292003) and then we use it for potentially async operations. This could explain some of the invalid values we sometimes get.
=> [ANDR] Copy jank framedata before using it

Cargo.Bazel.lock, Cargo.toml
This sets panic=abort for the cdylib when built via Gradle. This mirrors our setup with Bazel
Fixes BIT-5715
=> enable panic=abort for gradle build

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/ClientAttributes.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/FatalIssueReporterProcessor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ClientAttributesTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FatalIssueReporterProcessorTest.kt
Resolves BIT-5777, BIT-5246
Adding architecture, cpuAbis to Reports
[timeline session](https://timeline.bitdrift.dev/session/87c72347-ff73-4bb3-be27-b7c6052f0b57?utm_source=sdk&pages=1&utilization=0&expanded=2241004306869461929 )
=> [Android] Adding Architecture, supported ABIs to reports

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/NetworkAttributes.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/NetworkAttributesTest.kt
Tackling mainly:
This should make `start()` perform 11.18% faster
|Before|After|
|---|---|
|<img width="2204" height="934" alt="Screenshot 2025-07-17 at 9 59 14 AM (1)" src="https://github.com/user-attachments/assets/425a6433-b843-4ca7-b703-d85c8fe8e1e0" />|<img width="1139" height="421" alt="Screenshot 2025-07-17 at 12 36 30 PM" src="https://github.com/user-attachments/assets/474fc06a-4ac4-404a-b386-4fd211def9d4" />|
Session example testing the `SDKConfigured` log with the right `network_type` value: https://timeline.bitdrift.dev/session/fda02916-f33f-4365-8262-94d6132b2266?utm_source=sdk&pages=1&utilization=0&h=3450357454420969661
After the change this is the threading structure:
```
connectivityManager operations called in thread=io.bitdrift.capture.background-thread-worker …
```
=> [andr] Move expensive operations on start to a bg thread

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/CaptureJniLibrary.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
Resolves BIT-5887 (See [related context](https://bitdrift.slack.com/archives/C058ZD2M2CQ/p1753180710509879?thread_ts=1752696297.259089&cid=C058ZD2M2CQ) )
Adds another duration field for native load to the `SDKConfigured` log. This will help breaking down on production the overall `Capture.Logger.start` time
Verified on these sessions:
- [gradle test app session](https://timeline.bitdrift.dev/session/e04fbe48-5922-4f28-b4f3-f207b2f34c18?utm_source=sdk&pages=1&utilization=0&expanded=-7944603258184882928) with the GradleTest sample app
- [bazel release test app](https://timeline.bitdrift.dev/session/5f2bd465-a012-4fe0-b7fb-b374df283eb2?utm_source=sdk&pages=1&utilization=0&expanded=5496365138251104009)
=> [Android] Add native load duration to Capture SDK start log

.github/workflows/android.yaml, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
ubuntu-latest was updated to a newer NDK (kudos to @murki for the [source](https://github.com/actions/runner-images/pull/12630/files#diff-cc12e5c5d005932feaacf280af949d83e2cb6020dff8203d9ead2e00c30e8b7fL238))
Add new step to ensure the expected NDK version is installed
=> [Android] Fix ci issues due to NDK version change

bazel/android/build.bzl, platform/jvm/capture/BUILD.bazel, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/providers/FieldProvider.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/FieldProviderTest.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/utils/JavaMapInteroptIssue.java
Resolves BIT-5914
Prevents potential NPE if a map with null key/value is constructed via Java and passed into Capture.Logger calls
Verified with JUnit test with existing call and updated one. See [initial commit for demo](https://github.com/bitdriftlabs/capture-sdk/pull/519/commits/6302e3cb4ee1d6012f3d3e5ac9baa0d49323c947)
Temporary add this method call to GradleTestApp. App should not crash
=> [Android] Prevent interopt crash for toFields

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt
This change was accidentally merged when this PR was repurposed https://github.com/bitdriftlabs/capture-sdk/pull/521 😅
=> Remove accidental comment

.github/workflows/android.yaml
At the moment, forked repos can't post comments (e.g. apk size). See https://github.com/bitdriftlabs/capture-sdk/actions/runs/16567424226/job/46850978578?pr=529
For now skipping this step until we provide a token to run this on forked repos
=> Prevent ci failures from forked repos

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/LoggerImpl.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/providers/FieldProvider.kt
- In `LoggerImpl.extractFields`, skip creating a MapBuilder (capacity 8) and a HashMap(0) if throwable is null and fields is null or empty
- In `LoggerImpl.extractFields`, skip creating a MapBuilder AND a HashMap for every log with fields, directly create the target HashMap with the right capacity.
- In `Map.toFields()`, skip creating a HashMap(0) is map is empty.
=> Small optimization in LoggerImpl.extractFields

MODULE.bazel, MODULE.bazel.lock, platform/jvm/AndroidManifest.xml, platform/jvm/capture-apollo/build.gradle.kts, platform/jvm/capture-timber/build.gradle.kts, platform/jvm/capture/build.gradle.kts, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/NetworkAttributes.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/JvmCrashProcessor.kt, platform/jvm/common/AndroidManifest.xml, platform/jvm/common/build.gradle.kts, platform/jvm/gradle-test-app/build.gradle.kts, platform/jvm/microbenchmark/build.gradle.kts, platform/jvm/replay/AndroidManifest.xml, platform/jvm/replay/build.gradle.kts, tools/android_sdk_wrapper.sh
Only meaningful change is thread.id deprecation.
Verifications:
gradle-test-app
- session: https://timeline.bitdrift.dev/session/6ecb0d66-651a-492f-93f0-5562019fd437
- crash: https://explorations.bitdrift.dev/issues/9071216148438387721/4d316b88-ecf6-4428-ba9f-8e06af629969
bazel hello-world
- session: https://timeline.bitdrift.dev/session/d38adcd3-7c40-4034-a858-e13d580e996c
- crash: https://explorations.bitdrift.dev/issues/13877890032708306952/09d11014-de09-47d5-8225-fe279d7dc256
Fixes BIT-5560
=> [andr] Bump support to API 36 (Android 16)

.github/workflows/example_apps_android.yaml, .github/workflows/integrations_android.yaml
TDLR We can't release due to missing NDK https://github.com/bitdriftlabs/capture-sdk/actions/runs/16620259183/job/47022691775
Similar to https://github.com/bitdriftlabs/capture-sdk/pull/521 we need to install NDK for release scripts as well 
See https://github.com/actions/runner-images/pull/12630/files#diff-cc12e5c5d005932feaacf280af949d83e2cb6020dff8203d9ead2e00c30e8b7fL238
=> Install NDK for release scripts

.bazelrc, .github/workflows/android.yaml
This reverts commit 3fe3e2edf539deecdd2d5c1cfc3a94a75ba53188 to allow release
See [thread](https://bitdrift.slack.com/archives/C058ZD2M2CQ/p1753874835998939)
=> Revert "strip out Debug impls in release (#510)"

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/ClientAttributes.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/IClientAttributes.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/FatalIssueReporterProcessor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/ClientAttributesTest.kt
Resolves BIT-5976
We weren't passing os version to fatal issue reports
- Verified on this [report](https://explorations.bitdrift.dev/issues/10373950639727864931/e2202fec-e910-4ded-84b2-78e69b2fc51b?utm_source=sdk)
- Which matches reported with the associated [timeline session of the crash](https://timeline.bitdrift.dev/session/485762d9-0af0-49e0-8143-c77b9e85a2ff?utm_source=sdk&pages=1&utilization=0&expanded=-6379577480046148239)
=> [Android] Adding os version to fatal issue reports

gradle/build.gradle, gradle/settings.gradle
Until we publish our plugin to [gradle plugin portal](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html) this is the format customers need to follow in order to consume our plugin via maven central
=> [andr][examples] Use bitdrift plugin from maven central

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListener.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListenerFactory.kt, platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpRequestFieldProvider.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureOkHttpEventListenerFactoryTest.kt
This allows SDK consumers to inspect OkHttp requests right before they get logged to Bitdrift and provide extra fields to log.
Some notes & feedback on the code:
- I added a OkHttpRequestFieldProvider for extra fields on the request logs, but I didn't create a `OkHttpResponseFieldProvider`, because I have no use for that. You might want to do that, or merge those 2 and have one method for request and one for response (ideally I'd stick to 2 interfaces though, so that you can implement only what you need)
- CaptureOkHttpEventListenerFactory has 3 public constructors, which forced me to add this new param to all 3, with a default value. Ideally there would have been a single constructor, taking a `EventListener.Factory` defaulting to `{ NoOpEventListener }` (or accepting null but that's not …
=> Add OkHttpRequestFieldProvider to CaptureOkHttpEventListenerFactory

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/OkHttpApiClient.kt
Follow up to https://github.com/bitdriftlabs/capture-sdk/pull/180
Prevents `2025-08-05 19:39:00.410 okhttp.OkHttpClient      W  A connection to https://api.bitdrift.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: `
Checking logcat on PR, this warning should be gone 
[Network spans](https://timeline.bitdrift.dev/session/0fdac65a-d0cb-429f-af85-992294928a55?utm_source=sdk&pages=1&utilization=0#spans)
=> [Android] Fix OkHttpClient connection leaked

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/ClientAttributes.kt
- Replace getters with fields to avoid constantly recomputing
- Used direct fields for constant references, and lazy fields for values that were pulled out of a context
- Split the map of attributes into constant values & dynamic values to avoid building the map all the time
=> Optimize ClientAttributes

platform/swift/source/integrations/url_session/ProxyURLSessionDelegate.swift, platform/swift/source/integrations/url_session/extensions/URLSession+Extensions.swift, test/platform/swift/unit_integration/integrations/URLSessionIntegrationTests.swift
When a `delegate` is provided while using our `URLSession(instrumentedSessionWithConfiguration:delegate:delegateQueue:)` integration, we were assuming the delegate will always be a `URLSessionTaskDelegate` which fails silently if the provided delegate is a bare `URLSessionDelegate`.
This change proxies the events to `URLSessionDelegate`s too.
=> Fix non-task custom delegate

Cargo.Bazel.lock, Cargo.lock, Cargo.toml
Updates shared-core to bring in global state changes
The crash log now has all fields set via providers/addField
https://timeline.bitdrift.dev/session/365a0cd7-8ce9-483f-a875-a299a5a43e74?utm_source=sdk&expanded=4261826404135680677
=> bring in global state changes

platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/reports/processor/NativeCrashProcessorTest.kt
Since gradle blocks on warnings, running tests locally in Android Studio wasn't working
=> [andr] Fix running unit tests locally in IDE

examples/swift/hello_world/LoggerCustomer.swift, platform/jvm/gradle-test-app/src/main/java/io/bitdrift/gradletestapp/FirstFragment.kt, platform/swift/source/LoggerIntegrator.swift, platform/swift/source/integrations/url_session/URLSessionIntegration.swift, platform/swift/source/integrations/url_session/URLSessionRequestFieldProvider.swift, platform/swift/source/integrations/url_session/URLSessionTaskTracker.swift, platform/swift/source/logging/HTTPRequestInfo.swift, test/platform/swift/unit_integration/core/LoggerIntegratorTests.swift, test/platform/swift/unit_integration/core/LoggerSharedTests.swift, test/platform/swift/unit_integration/core/bindings/HTTPRequestInfo+ExtensionsTests.swift, test/platform/swift/unit_integration/core/logging/HTTPRequestInfoTests.swift
Resolves BIT-6252
Bring parity on iOS with the recent Android addition added in https://github.com/bitdriftlabs/capture-sdk/pull/540 which support adding custom fields to network requests
Check sample app session below with network requests /responses that now contains `additional_network_request_field`
| OS type | Image |
|-----|-------|
| [iOS Session](https://timeline.bitdrift.dev/session/DC632123-8838-4B27-A917-72B0CDEEF010?utm_source=sdk&pages=1&utilization=0&expanded=7272735427352928998) | <img width="422" height="87" alt="image" src="https://github.com/user-attachments/assets/0988c60a-c88b-4ca1-94d1-82bd794182fe" /> |
| [Android Session](https://timeline.bitdrift.dev/session/a8b42467-fd68-4e4c-8535-1adbd049f79b?utm_source=sdk&pages=1&utilization=0&expanded=-930040541736966171) | …
=> [iOS] Provide custom fields to network requests

BUILD, bazel/android/artifacts.bzl, bazel/android_debug_info.bzl
=> Use objcopy instead of dump for symbols

Cargo.Bazel.lock, Cargo.lock, Cargo.toml
Bump shared-core for https://github.com/bitdriftlabs/shared-core/pull/224
[Android Gradle Test session](https://timeline.bitdrift.dev/session/4fda8892-8e75-47ca-9e28-b2a3e0aa929a?utm_source=sdk&pages=1&utilization=0&expanded=6928725493811316135)
[Android Bazel Test session](https://timeline.bitdrift.dev/session/e79e82ed-1fc7-499f-b79e-c6f47bc0e993?utm_source=sdk&pages=1&utilization=0&expanded=5640934324172272429)
[iOS Test session](https://timeline.bitdrift.dev/session/227C5F17-E663-4BEA-A7E4-6E37282AAF4B?utm_source=sdk)
=> Bump shared-core for better rate limiting backoff

MODULE.bazel
I've updated KSCrash to make it play nicer with other crash handlers:
* [698](https://github.com/kstenerud/KSCrash/pull/698): Be more conservative when uninstalling after a crash. There were edge cases where it could end up calling an already uninstalled handler, leading to undefined behavior.
* [699](https://github.com/kstenerud/KSCrash/pull/699): Namespace any public facing strings (such as thread names) so that it's clear which library they belong to.
=> Update to latest KSCrash

platform/shared/build.rs
This invalidates the output of the build.rs when .sdk_version changes
=> rerun build.rs when .sdk_version changes

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/reports/processor/NativeCrashProcessor.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/reports/processor/NativeCrashProcessorTest.kt
Instead of only including binary images with a valid build ID, synthesize a binary image for each mapped region referred to by the stack trace. This ensures that we have all the information we need for all frames, even if they don't have a build ID
=> include all binary images from android tombstones

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/attributes/ClientAttributes.kt
Follow up to https://github.com/bitdriftlabs/capture-sdk/pull/558
In this case we avoid creating new map upon each `invoke` call and use the priorly cache map with foreground/background event
| Main | PR |
| ------| ------|
| <img width="1205" height="171" alt="image" src="https://github.com/user-attachments/assets/02005868-5162-449b-b580-3cacf596eff3" /> | <img width="1194" height="184" alt="image" src="https://github.com/user-attachments/assets/2433dc85-2429-48dc-ab11-d88405f404e2" /> |
| 10999 allocs | 0 allocs |
=> Client attributes perf improvements

platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/CaptureTokioThreadTest.kt, platform/jvm/src/jni.rs
Previously we attempted to fix an issue where the JVM would override the name that we assigned to the tokio event loop thread by updating the name of the native thread. This would leave the JVM thread name unchanged, resulting in an unnamed thread from the perspective of the JVM.
To fix this, use the JVM Thread.setName function to update both the JVM and native thred name
Fixes BIT-6500
=> use Thread.setName to update tokio thread name

platform/jvm/src/jni.rs
This logs an error log with the cause whenever JNI_OnLoad fails. This should never fail on real devices so this is meant mostly to help debugging this in test.
This now logs something like 
```
2025-10-02 11:37:45.404 26684-26684 capture::jni            io.bitdrift.gradletestapp            E  failed with exception java.lang.NoSuchMethodError: no non-static method "Lio/bitdrift/capture/providers/Field;.getKe()Ljava/lang/String;"
2025-10-02 11:37:45.404 26684-26684 capture::jni            io.bitdrift.gradletestapp            E  JNI_OnLoad failed: failed to resolve method
````
=> log failure reason if JNI_OnLoad fails

platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListenerFactory.kt, platform/jvm/capture/src/test/kotlin/io/bitdrift/capture/network/okhttp/CaptureOkHttpEventListenerFactoryTest.kt
Resolves BIT-6600
For cases where the customer doesn't initialize SDK we shouldn't create CaptureOkHttpEventListener 
- Use gradle-test-app with `Deferred SDK Start` setting and verify that OkHttp event listener events starts getting collected upon initialization. See [session here ](https://timeline.bitdrift.dev/session/640abab9-ce4d-4bd2-b9f6-0e6545f3cef5?utm_source=sdk&utilization=0&expanded=-1422884516528367511#timeline)
- Once SDK initialized verify network spans are correctly captured
=> Avoid creating a CaptureOkHttpEventListener if SDK is not initialized
